# 読みのソート、コメントのみの行の削除を行う
name: build

on:
  push:
    branches:
      - master
    paths:
      - src/SKK-JISYO.kancolle
      - .github/workflows/build.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          # コミット最終日時を取得
          LAST_MODIFIED=$(git log --date=format:"%b. %-d, %Y" --pretty=format:"%cd" -1 ./src/SKK-JISYO.kancolle)
          # 43 - 45行目を削除して、読みのソートを行った結果をbuildディレクトリに出力
          sed -e 43,45d -e "s/%LAST_MODIFIED%/${LAST_MODIFIED}/" ./src/SKK-JISYO.kancolle | docker run --rm -i ghcr.io/mtgto/skkdic-sort:latest > ./build/SKK-JISYO.kancolle
          if ! git diff --exit-code --quiet ./build/SKK-JISYO.kancolle; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add ./build/SKK-JISYO.kancolle
            git commit -m "Automatic Build"
            git push
          fi
